#!/bin/bash

sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/listener.ora

while true; do
	status=`ps -ef | grep tns | grep oracle`
	pmon=`ps -ef | egrep pmon_$ORACLE_SID'\>' | grep -v grep`
	if [ "$status" == "" ] || [ "$pmon" == "" ]
	then
		service=oracle-${ORACLE_SID,,}		
		service $service start
		service $service status
	fi
	sleep 1m
done;

